//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gelir_Gider_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class GELIR_GIDER_KAYITLARI
    {
        public int ggr_ID { get; set; }
        public Nullable<System.DateTime> ggr_tarih { get; set; }
        public string ggr_tipi { get; set; }
        public string ggr_gider_tipi { get; set; }
        public Nullable<double> ggr_tutar { get; set; }
        public string ggr_aciklama { get; set; }
        public Nullable<System.DateTime> ggr_kayit_tarih { get; set; }
    }
}
