//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gelir_Gider_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIDER_TIPLERI
    {
        public int gdr_ID { get; set; }
        public string gdr_Gider_Kod { get; set; }
        public string gdr_Gider_Ad { get; set; }
    }
}
